services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    expose:
      - "3000"
    env_file:
      - ./api/.env.local
    environment:
      - PORT=3000

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api
